/**
 * ============================================================================
 * CART DRAWER — Slide-in cart panel
 * ============================================================================
 *
 * SHOPIFY CONNECTION POINTS:
 * - Cart state: synced with Shopify via Storefront Cart API (see cartStore.ts)
 * - Cart items: each has a lineId from Shopify for update/remove operations
 * - Checkout: redirects to Shopify checkout via checkoutUrl from cartCreate
 * - Upsell: "Det giver mening sammen med…" — connect to product recommendations
 * - Trust/shipping: customize thresholds based on Shopify shipping rules
 *
 * CHECKOUT FLOW:
 * 1. User adds items → cartCreate mutation creates Shopify cart
 * 2. Subsequent adds → cartLinesAdd mutation
 * 3. "Gå til betaling" → window.open(checkoutUrl, '_blank')
 * 4. checkoutUrl includes channel=online_store parameter
 * ============================================================================
 */

import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Minus, Plus, Trash2, Loader2, ArrowRight, ShieldCheck } from "lucide-react";
import { useCartStore } from "@/stores/cartStore";
import { formatPrice } from "@/lib/shopify";

/** Free shipping threshold in store currency (DKK) */
const FREE_SHIPPING_THRESHOLD = 499;

export function CartDrawer() {
  const { items, isLoading, isSyncing, isOpen, setOpen, updateQuantity, removeItem, getCheckoutUrl, syncCart } = useCartStore();
  const totalItems = items.reduce((sum, item) => sum + item.quantity, 0);
  const totalPrice = items.reduce((sum, item) => sum + parseFloat(item.price.amount) * item.quantity, 0);
  const currency = items[0]?.price.currencyCode || 'DKK';
  const remainingForFreeShipping = Math.max(0, FREE_SHIPPING_THRESHOLD - totalPrice);

  /**
   * SHOPIFY CONNECTION: Checkout redirect.
   * The checkoutUrl is generated by the Storefront Cart API cartCreate mutation.
   * It includes channel=online_store to bypass store password protection.
   * Opens in a new tab — the cart syncs on tab focus return (see useCartSync).
   */
  const handleCheckout = () => {
    const url = getCheckoutUrl();
    if (url) {
      window.open(url, '_blank');
      setOpen(false);
    }
  };

  return (
    <Sheet open={isOpen} onOpenChange={(o) => { setOpen(o); if (o) syncCart(); }}>
      <SheetContent className="w-full sm:max-w-md flex flex-col h-full bg-background border-l border-border">
        <SheetHeader className="flex-shrink-0 pb-4 border-b border-border">
          <SheetTitle className="font-serif text-xl">Dit ritual</SheetTitle>
          <p className="text-sm text-muted-foreground">
            {totalItems === 0 ? "Din kurv er tom" : `${totalItems} ${totalItems === 1 ? 'genstand' : 'genstande'}`}
          </p>
        </SheetHeader>

        <div className="flex flex-col flex-1 min-h-0 pt-4">
          {items.length === 0 ? (
           <div className="flex-1 flex items-center justify-center">
              <div className="text-center px-6">
                <p className="font-serif text-lg text-muted-foreground mb-2">Dit ritual er endnu ikke begyndt.</p>
                <p className="text-sm text-muted-foreground/70">
                  Udforsk vores køkkenritualer og find dit første værktøj.
                </p>
              </div>
            </div>
          ) : (
            <>
              {/* Free shipping progress */}
              {totalPrice > 0 && (
                <div className="mb-4 px-1">
                  {remainingForFreeShipping > 0 ? (
                    <p className="text-xs text-muted-foreground text-center mb-2">
                      Du er tæt på fri fragt. Tilføj pleje eller tilbehør, hvis det giver mening for dit ritual.
                    </p>
                  ) : (
                    <p className="text-xs text-cta text-center mb-2 font-medium">
                      ✓ Du har fri fragt
                    </p>
                  )}
                  <div className="h-1 bg-border rounded-full overflow-hidden">
                    <div
                      className="h-full bg-cta rounded-full transition-all duration-500"
                      style={{ width: `${Math.min(100, (totalPrice / FREE_SHIPPING_THRESHOLD) * 100)}%` }}
                    />
                  </div>
                </div>
              )}

              {/* Cart items */}
              <div className="flex-1 overflow-y-auto space-y-4 pr-1">
                {items.map((item) => (
                  <div key={item.variantId} className="flex gap-4 p-3 rounded-lg bg-soft/50">
                    {/* SHOPIFY CONNECTION: Product image from Shopify CDN */}
                    <div className="w-20 h-20 rounded-md overflow-hidden flex-shrink-0 bg-linen">
                      {item.product.node.images?.edges?.[0]?.node && (
                        <img
                          src={item.product.node.images.edges[0].node.url}
                          alt={item.product.node.title}
                          className="w-full h-full object-cover"
                        />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="font-medium text-sm leading-tight">{item.product.node.title}</h4>
                      {item.variantTitle !== "Default Title" && (
                        <p className="text-xs text-muted-foreground mt-0.5">{item.variantTitle}</p>
                      )}
                      <p className="text-sm font-medium mt-1">
                        {formatPrice(item.price.amount, item.price.currencyCode)}
                      </p>
                      {/* SHOPIFY CONNECTION: Quantity updates via cartLinesUpdate mutation */}
                      <div className="flex items-center gap-2 mt-2">
                        <button
                          onClick={() => updateQuantity(item.variantId, item.quantity - 1)}
                          className="w-7 h-7 rounded-md border border-border flex items-center justify-center hover:bg-accent transition-colors"
                        >
                          <Minus className="w-3 h-3" />
                        </button>
                        <span className="text-sm w-6 text-center">{item.quantity}</span>
                        <button
                          onClick={() => updateQuantity(item.variantId, item.quantity + 1)}
                          className="w-7 h-7 rounded-md border border-border flex items-center justify-center hover:bg-accent transition-colors"
                        >
                          <Plus className="w-3 h-3" />
                        </button>
                        {/* SHOPIFY CONNECTION: Remove via cartLinesRemove mutation */}
                        <button
                          onClick={() => removeItem(item.variantId)}
                          className="ml-auto text-muted-foreground hover:text-foreground transition-colors"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* ── Upsell Block ──────────────────────────────────────────
                  SHOPIFY CONNECTION: Connect to product recommendations API.
                  Use fetchProductRecommendations() with the first cart item's product ID
                  to show contextual upsells.
                  ──────────────────────────────────────────────────────────── */}
              <div className="flex-shrink-0 py-3 border-t border-border">
                <p className="text-xs text-muted-foreground font-medium mb-2 px-1">
                  Det giver mening sammen med…
                </p>
                <div className="flex gap-2 overflow-x-auto pb-1 px-1">
                  {/* SHOPIFY CONNECTION: Replace these placeholders with product recommendations */}
                  {['Plejeolie', 'Slibesten #1000', 'Magnetisk holder'].map((name) => (
                    <div
                      key={name}
                      className="flex-shrink-0 px-3 py-2 rounded-md border border-border bg-soft/30 text-xs text-muted-foreground hover:border-walnut/30 transition-colors cursor-pointer"
                    >
                      + {name}
                    </div>
                  ))}
                </div>
              </div>

              {/* Checkout footer */}
              <div className="flex-shrink-0 pt-4 border-t border-border space-y-4">
                {/* Secure payment info box */}
                <div className="rounded-lg p-4 bg-soft/40 border border-foreground/10">
                  <div className="flex items-start gap-2.5">
                    <ShieldCheck className="w-4 h-4 text-cta mt-0.5 flex-shrink-0" strokeWidth={1.5} />
                    <div>
                      <p className="text-xs font-medium text-foreground mb-1">Sikker betaling</p>
                      <p className="text-xs text-muted-foreground leading-relaxed">
                        Du betaler trygt via Shopify checkout. Betalingsmulighederne vises, når du går videre til checkout.
                      </p>
                    </div>
                  </div>
                </div>

                <p className="text-xs text-muted-foreground text-center italic">
                  Din ordre pakkes med ro og omhu.
                </p>
                <div className="flex justify-between items-baseline">
                  <span className="text-sm text-muted-foreground">Subtotal</span>
                  <span className="text-lg font-serif font-medium">
                    {formatPrice(totalPrice.toString(), currency)}
                  </span>
                </div>
                {/* SHOPIFY CONNECTION: Checkout redirect via Storefront Cart API */}
                <Button
                  variant="cta"
                  size="lg"
                  className="w-full"
                  onClick={handleCheckout}
                  disabled={items.length === 0 || isLoading || isSyncing}
                >
                  {isLoading || isSyncing ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <>
                      Gå til betaling
                      <ArrowRight className="w-4 h-4 ml-2" />
                    </>
                  )}
                </Button>
                <p className="text-xs text-muted-foreground text-center">
                  Betaling håndteres sikkert i checkout.
                </p>
                <div className="flex justify-center gap-6 text-xs text-muted-foreground">
                  <span>Pakket med omhu</span>
                  <span>·</span>
                  <span>Sikker betaling</span>
                  <span>·</span>
                  <span>30 dages returret</span>
                </div>
                <button
                  onClick={() => setOpen(false)}
                  className="w-full text-center text-sm text-muted-foreground hover:text-foreground transition-colors pt-2"
                >
                  Fortsæt med at udforske
                </button>
              </div>
            </>
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}
