/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversetRouteImport } from './routes/universet'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ReturpolitikRouteImport } from './routes/returpolitik'
import { Route as ReklamationRouteImport } from './routes/reklamation'
import { Route as PrivatlivspolitikRouteImport } from './routes/privatlivspolitik'
import { Route as OmRouteImport } from './routes/om'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as HandelsbetingelserRouteImport } from './routes/handelsbetingelser'
import { Route as FragtRouteImport } from './routes/fragt'
import { Route as FindDitRitualRouteImport } from './routes/find-dit-ritual'
import { Route as CookiepolitikRouteImport } from './routes/cookiepolitik'
import { Route as CirklenRouteImport } from './routes/cirklen'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeramikIndexRouteImport } from './routes/keramik.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as UniversetSlugRouteImport } from './routes/universet_.$slug'
import { Route as RitualerRoligOpbevaringRouteImport } from './routes/ritualer.rolig-opbevaring'
import { Route as RitualerHoldKnivenSkarpRouteImport } from './routes/ritualer.hold-kniven-skarp'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as PagesSommerbordMedKeramikRouteImport } from './routes/pages.sommerbord-med-keramik'
import { Route as PagesSlibestenGuideRouteImport } from './routes/pages.slibesten-guide'
import { Route as PagesSadanHolderDuDinKnivSkarpRouteImport } from './routes/pages.sadan-holder-du-din-kniv-skarp'
import { Route as PagesSaadanSliberDuDinKnivRouteImport } from './routes/pages.saadan-sliber-du-din-kniv'
import { Route as PagesKoekkenetSomFristedRouteImport } from './routes/pages.koekkenet-som-fristed'
import { Route as PagesKnivholderTilKoekkenetRouteImport } from './routes/pages.knivholder-til-koekkenet'
import { Route as PagesKnivholderITraeRouteImport } from './routes/pages.knivholder-i-trae'
import { Route as PagesHvilkenKnivholderSkalJegVaelgeRouteImport } from './routes/pages.hvilken-knivholder-skal-jeg-vaelge'
import { Route as PagesHaandlavetKeramikRouteImport } from './routes/pages.haandlavet-keramik'
import { Route as PagesGaverMedRoRouteImport } from './routes/pages.gaver-med-ro'
import { Route as PagesGaveTilMadelskerenRouteImport } from './routes/pages.gave-til-madelskeren'
import { Route as PagesDenForsteRigtigeKokkeknivRouteImport } from './routes/pages.den-forste-rigtige-kokkekniv'
import { Route as PagesDamaskusKnivRouteImport } from './routes/pages.damaskus-kniv'
import { Route as KeramikSusanRielRouteImport } from './routes/keramik.susan-riel'
import { Route as KeramikSlugRouteImport } from './routes/keramik.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as GaverFarsDagRouteImport } from './routes/gaver.fars-dag'
import { Route as CollectionsHandlavetKeramikRouteImport } from './routes/collections.handlavet-keramik'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'

const UniversetRoute = UniversetRouteImport.update({
  id: '/universet',
  path: '/universet',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturpolitikRoute = ReturpolitikRouteImport.update({
  id: '/returpolitik',
  path: '/returpolitik',
  getParentRoute: () => rootRouteImport,
} as any)
const ReklamationRoute = ReklamationRouteImport.update({
  id: '/reklamation',
  path: '/reklamation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlivspolitikRoute = PrivatlivspolitikRouteImport.update({
  id: '/privatlivspolitik',
  path: '/privatlivspolitik',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const HandelsbetingelserRoute = HandelsbetingelserRouteImport.update({
  id: '/handelsbetingelser',
  path: '/handelsbetingelser',
  getParentRoute: () => rootRouteImport,
} as any)
const FragtRoute = FragtRouteImport.update({
  id: '/fragt',
  path: '/fragt',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDitRitualRoute = FindDitRitualRouteImport.update({
  id: '/find-dit-ritual',
  path: '/find-dit-ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiepolitikRoute = CookiepolitikRouteImport.update({
  id: '/cookiepolitik',
  path: '/cookiepolitik',
  getParentRoute: () => rootRouteImport,
} as any)
const CirklenRoute = CirklenRouteImport.update({
  id: '/cirklen',
  path: '/cirklen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeramikIndexRoute = KeramikIndexRouteImport.update({
  id: '/keramik/',
  path: '/keramik/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversetSlugRoute = UniversetSlugRouteImport.update({
  id: '/universet_/$slug',
  path: '/universet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualerRoligOpbevaringRoute = RitualerRoligOpbevaringRouteImport.update({
  id: '/ritualer/rolig-opbevaring',
  path: '/ritualer/rolig-opbevaring',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualerHoldKnivenSkarpRoute = RitualerHoldKnivenSkarpRouteImport.update({
  id: '/ritualer/hold-kniven-skarp',
  path: '/ritualer/hold-kniven-skarp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSommerbordMedKeramikRoute =
  PagesSommerbordMedKeramikRouteImport.update({
    id: '/pages/sommerbord-med-keramik',
    path: '/pages/sommerbord-med-keramik',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesSlibestenGuideRoute = PagesSlibestenGuideRouteImport.update({
  id: '/pages/slibesten-guide',
  path: '/pages/slibesten-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSadanHolderDuDinKnivSkarpRoute =
  PagesSadanHolderDuDinKnivSkarpRouteImport.update({
    id: '/pages/sadan-holder-du-din-kniv-skarp',
    path: '/pages/sadan-holder-du-din-kniv-skarp',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesSaadanSliberDuDinKnivRoute =
  PagesSaadanSliberDuDinKnivRouteImport.update({
    id: '/pages/saadan-sliber-du-din-kniv',
    path: '/pages/saadan-sliber-du-din-kniv',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesKoekkenetSomFristedRoute =
  PagesKoekkenetSomFristedRouteImport.update({
    id: '/pages/koekkenet-som-fristed',
    path: '/pages/koekkenet-som-fristed',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesKnivholderTilKoekkenetRoute =
  PagesKnivholderTilKoekkenetRouteImport.update({
    id: '/pages/knivholder-til-koekkenet',
    path: '/pages/knivholder-til-koekkenet',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesKnivholderITraeRoute = PagesKnivholderITraeRouteImport.update({
  id: '/pages/knivholder-i-trae',
  path: '/pages/knivholder-i-trae',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHvilkenKnivholderSkalJegVaelgeRoute =
  PagesHvilkenKnivholderSkalJegVaelgeRouteImport.update({
    id: '/pages/hvilken-knivholder-skal-jeg-vaelge',
    path: '/pages/hvilken-knivholder-skal-jeg-vaelge',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesHaandlavetKeramikRoute = PagesHaandlavetKeramikRouteImport.update({
  id: '/pages/haandlavet-keramik',
  path: '/pages/haandlavet-keramik',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesGaverMedRoRoute = PagesGaverMedRoRouteImport.update({
  id: '/pages/gaver-med-ro',
  path: '/pages/gaver-med-ro',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesGaveTilMadelskerenRoute = PagesGaveTilMadelskerenRouteImport.update({
  id: '/pages/gave-til-madelskeren',
  path: '/pages/gave-til-madelskeren',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDenForsteRigtigeKokkeknivRoute =
  PagesDenForsteRigtigeKokkeknivRouteImport.update({
    id: '/pages/den-forste-rigtige-kokkekniv',
    path: '/pages/den-forste-rigtige-kokkekniv',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesDamaskusKnivRoute = PagesDamaskusKnivRouteImport.update({
  id: '/pages/damaskus-kniv',
  path: '/pages/damaskus-kniv',
  getParentRoute: () => rootRouteImport,
} as any)
const KeramikSusanRielRoute = KeramikSusanRielRouteImport.update({
  id: '/susan-riel',
  path: '/susan-riel',
  getParentRoute: () => KeramikRoute,
} as any)
const KeramikSlugRoute = KeramikSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KeramikRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GaverFarsDagRoute = GaverFarsDagRouteImport.update({
  id: '/gaver/fars-dag',
  path: '/gaver/fars-dag',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandlavetKeramikRoute =
  CollectionsHandlavetKeramikRouteImport.update({
    id: '/collections/handlavet-keramik',
    path: '/collections/handlavet-keramik',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cirklen': typeof CirklenRoute
  '/cookiepolitik': typeof CookiepolitikRoute
  '/find-dit-ritual': typeof FindDitRitualRoute
  '/fragt': typeof FragtRoute
  '/handelsbetingelser': typeof HandelsbetingelserRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/reklamation': typeof ReklamationRoute
  '/returpolitik': typeof ReturpolitikRoute
  '/shop': typeof ShopRoute
  '/universet': typeof UniversetRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/collections/handlavet-keramik': typeof CollectionsHandlavetKeramikRoute
  '/gaver/fars-dag': typeof GaverFarsDagRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/keramik/$slug': typeof KeramikSlugRoute
  '/keramik/susan-riel': typeof KeramikSusanRielRoute
  '/pages/damaskus-kniv': typeof PagesDamaskusKnivRoute
  '/pages/den-forste-rigtige-kokkekniv': typeof PagesDenForsteRigtigeKokkeknivRoute
  '/pages/gave-til-madelskeren': typeof PagesGaveTilMadelskerenRoute
  '/pages/gaver-med-ro': typeof PagesGaverMedRoRoute
  '/pages/haandlavet-keramik': typeof PagesHaandlavetKeramikRoute
  '/pages/hvilken-knivholder-skal-jeg-vaelge': typeof PagesHvilkenKnivholderSkalJegVaelgeRoute
  '/pages/knivholder-i-trae': typeof PagesKnivholderITraeRoute
  '/pages/knivholder-til-koekkenet': typeof PagesKnivholderTilKoekkenetRoute
  '/pages/koekkenet-som-fristed': typeof PagesKoekkenetSomFristedRoute
  '/pages/saadan-sliber-du-din-kniv': typeof PagesSaadanSliberDuDinKnivRoute
  '/pages/sadan-holder-du-din-kniv-skarp': typeof PagesSadanHolderDuDinKnivSkarpRoute
  '/pages/slibesten-guide': typeof PagesSlibestenGuideRoute
  '/pages/sommerbord-med-keramik': typeof PagesSommerbordMedKeramikRoute
  '/product/$handle': typeof ProductHandleRoute
  '/ritualer/hold-kniven-skarp': typeof RitualerHoldKnivenSkarpRoute
  '/ritualer/rolig-opbevaring': typeof RitualerRoligOpbevaringRoute
  '/universet/$slug': typeof UniversetSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/keramik/': typeof KeramikIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cirklen': typeof CirklenRoute
  '/cookiepolitik': typeof CookiepolitikRoute
  '/find-dit-ritual': typeof FindDitRitualRoute
  '/fragt': typeof FragtRoute
  '/handelsbetingelser': typeof HandelsbetingelserRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/reklamation': typeof ReklamationRoute
  '/returpolitik': typeof ReturpolitikRoute
  '/shop': typeof ShopRoute
  '/universet': typeof UniversetRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/collections/handlavet-keramik': typeof CollectionsHandlavetKeramikRoute
  '/gaver/fars-dag': typeof GaverFarsDagRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/keramik/$slug': typeof KeramikSlugRoute
  '/keramik/susan-riel': typeof KeramikSusanRielRoute
  '/pages/damaskus-kniv': typeof PagesDamaskusKnivRoute
  '/pages/den-forste-rigtige-kokkekniv': typeof PagesDenForsteRigtigeKokkeknivRoute
  '/pages/gave-til-madelskeren': typeof PagesGaveTilMadelskerenRoute
  '/pages/gaver-med-ro': typeof PagesGaverMedRoRoute
  '/pages/haandlavet-keramik': typeof PagesHaandlavetKeramikRoute
  '/pages/hvilken-knivholder-skal-jeg-vaelge': typeof PagesHvilkenKnivholderSkalJegVaelgeRoute
  '/pages/knivholder-i-trae': typeof PagesKnivholderITraeRoute
  '/pages/knivholder-til-koekkenet': typeof PagesKnivholderTilKoekkenetRoute
  '/pages/koekkenet-som-fristed': typeof PagesKoekkenetSomFristedRoute
  '/pages/saadan-sliber-du-din-kniv': typeof PagesSaadanSliberDuDinKnivRoute
  '/pages/sadan-holder-du-din-kniv-skarp': typeof PagesSadanHolderDuDinKnivSkarpRoute
  '/pages/slibesten-guide': typeof PagesSlibestenGuideRoute
  '/pages/sommerbord-med-keramik': typeof PagesSommerbordMedKeramikRoute
  '/product/$handle': typeof ProductHandleRoute
  '/ritualer/hold-kniven-skarp': typeof RitualerHoldKnivenSkarpRoute
  '/ritualer/rolig-opbevaring': typeof RitualerRoligOpbevaringRoute
  '/universet/$slug': typeof UniversetSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/keramik': typeof KeramikIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cirklen': typeof CirklenRoute
  '/cookiepolitik': typeof CookiepolitikRoute
  '/find-dit-ritual': typeof FindDitRitualRoute
  '/fragt': typeof FragtRoute
  '/handelsbetingelser': typeof HandelsbetingelserRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/reklamation': typeof ReklamationRoute
  '/returpolitik': typeof ReturpolitikRoute
  '/shop': typeof ShopRoute
  '/universet': typeof UniversetRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/collections/handlavet-keramik': typeof CollectionsHandlavetKeramikRoute
  '/gaver/fars-dag': typeof GaverFarsDagRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/keramik/$slug': typeof KeramikSlugRoute
  '/keramik/susan-riel': typeof KeramikSusanRielRoute
  '/pages/damaskus-kniv': typeof PagesDamaskusKnivRoute
  '/pages/den-forste-rigtige-kokkekniv': typeof PagesDenForsteRigtigeKokkeknivRoute
  '/pages/gave-til-madelskeren': typeof PagesGaveTilMadelskerenRoute
  '/pages/gaver-med-ro': typeof PagesGaverMedRoRoute
  '/pages/haandlavet-keramik': typeof PagesHaandlavetKeramikRoute
  '/pages/hvilken-knivholder-skal-jeg-vaelge': typeof PagesHvilkenKnivholderSkalJegVaelgeRoute
  '/pages/knivholder-i-trae': typeof PagesKnivholderITraeRoute
  '/pages/knivholder-til-koekkenet': typeof PagesKnivholderTilKoekkenetRoute
  '/pages/koekkenet-som-fristed': typeof PagesKoekkenetSomFristedRoute
  '/pages/saadan-sliber-du-din-kniv': typeof PagesSaadanSliberDuDinKnivRoute
  '/pages/sadan-holder-du-din-kniv-skarp': typeof PagesSadanHolderDuDinKnivSkarpRoute
  '/pages/slibesten-guide': typeof PagesSlibestenGuideRoute
  '/pages/sommerbord-med-keramik': typeof PagesSommerbordMedKeramikRoute
  '/product/$handle': typeof ProductHandleRoute
  '/ritualer/hold-kniven-skarp': typeof RitualerHoldKnivenSkarpRoute
  '/ritualer/rolig-opbevaring': typeof RitualerRoligOpbevaringRoute
  '/universet_/$slug': typeof UniversetSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/keramik/': typeof KeramikIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/cirklen'
    | '/cookiepolitik'
    | '/find-dit-ritual'
    | '/fragt'
    | '/handelsbetingelser'
    | '/kontakt'
    | '/om'
    | '/privatlivspolitik'
    | '/reklamation'
    | '/returpolitik'
    | '/shop'
    | '/universet'
    | '/collections/$handle'
    | '/collections/handlavet-keramik'
    | '/gaver/fars-dag'
    | '/guides/$slug'
    | '/keramik/$slug'
    | '/keramik/susan-riel'
    | '/pages/damaskus-kniv'
    | '/pages/den-forste-rigtige-kokkekniv'
    | '/pages/gave-til-madelskeren'
    | '/pages/gaver-med-ro'
    | '/pages/haandlavet-keramik'
    | '/pages/hvilken-knivholder-skal-jeg-vaelge'
    | '/pages/knivholder-i-trae'
    | '/pages/knivholder-til-koekkenet'
    | '/pages/koekkenet-som-fristed'
    | '/pages/saadan-sliber-du-din-kniv'
    | '/pages/sadan-holder-du-din-kniv-skarp'
    | '/pages/slibesten-guide'
    | '/pages/sommerbord-med-keramik'
    | '/product/$handle'
    | '/ritualer/hold-kniven-skarp'
    | '/ritualer/rolig-opbevaring'
    | '/universet/$slug'
    | '/guides/'
    | '/keramik/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/cirklen'
    | '/cookiepolitik'
    | '/find-dit-ritual'
    | '/fragt'
    | '/handelsbetingelser'
    | '/kontakt'
    | '/om'
    | '/privatlivspolitik'
    | '/reklamation'
    | '/returpolitik'
    | '/shop'
    | '/universet'
    | '/collections/$handle'
    | '/collections/handlavet-keramik'
    | '/gaver/fars-dag'
    | '/guides/$slug'
    | '/keramik/$slug'
    | '/keramik/susan-riel'
    | '/pages/damaskus-kniv'
    | '/pages/den-forste-rigtige-kokkekniv'
    | '/pages/gave-til-madelskeren'
    | '/pages/gaver-med-ro'
    | '/pages/haandlavet-keramik'
    | '/pages/hvilken-knivholder-skal-jeg-vaelge'
    | '/pages/knivholder-i-trae'
    | '/pages/knivholder-til-koekkenet'
    | '/pages/koekkenet-som-fristed'
    | '/pages/saadan-sliber-du-din-kniv'
    | '/pages/sadan-holder-du-din-kniv-skarp'
    | '/pages/slibesten-guide'
    | '/pages/sommerbord-med-keramik'
    | '/product/$handle'
    | '/ritualer/hold-kniven-skarp'
    | '/ritualer/rolig-opbevaring'
    | '/universet/$slug'
    | '/guides'
    | '/keramik'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/cirklen'
    | '/cookiepolitik'
    | '/find-dit-ritual'
    | '/fragt'
    | '/handelsbetingelser'
    | '/kontakt'
    | '/om'
    | '/privatlivspolitik'
    | '/reklamation'
    | '/returpolitik'
    | '/shop'
    | '/universet'
    | '/collections/$handle'
    | '/collections/handlavet-keramik'
    | '/gaver/fars-dag'
    | '/guides/$slug'
    | '/keramik/$slug'
    | '/keramik/susan-riel'
    | '/pages/damaskus-kniv'
    | '/pages/den-forste-rigtige-kokkekniv'
    | '/pages/gave-til-madelskeren'
    | '/pages/gaver-med-ro'
    | '/pages/haandlavet-keramik'
    | '/pages/hvilken-knivholder-skal-jeg-vaelge'
    | '/pages/knivholder-i-trae'
    | '/pages/knivholder-til-koekkenet'
    | '/pages/koekkenet-som-fristed'
    | '/pages/saadan-sliber-du-din-kniv'
    | '/pages/sadan-holder-du-din-kniv-skarp'
    | '/pages/slibesten-guide'
    | '/pages/sommerbord-med-keramik'
    | '/product/$handle'
    | '/ritualer/hold-kniven-skarp'
    | '/ritualer/rolig-opbevaring'
    | '/universet_/$slug'
    | '/guides/'
    | '/keramik/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CirklenRoute: typeof CirklenRoute
  CookiepolitikRoute: typeof CookiepolitikRoute
  FindDitRitualRoute: typeof FindDitRitualRoute
  FragtRoute: typeof FragtRoute
  HandelsbetingelserRoute: typeof HandelsbetingelserRoute
  KontaktRoute: typeof KontaktRoute
  OmRoute: typeof OmRoute
  PrivatlivspolitikRoute: typeof PrivatlivspolitikRoute
  ReklamationRoute: typeof ReklamationRoute
  ReturpolitikRoute: typeof ReturpolitikRoute
  ShopRoute: typeof ShopRoute
  UniversetRoute: typeof UniversetRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  CollectionsHandlavetKeramikRoute: typeof CollectionsHandlavetKeramikRoute
  GaverFarsDagRoute: typeof GaverFarsDagRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PagesDamaskusKnivRoute: typeof PagesDamaskusKnivRoute
  PagesDenForsteRigtigeKokkeknivRoute: typeof PagesDenForsteRigtigeKokkeknivRoute
  PagesGaveTilMadelskerenRoute: typeof PagesGaveTilMadelskerenRoute
  PagesGaverMedRoRoute: typeof PagesGaverMedRoRoute
  PagesHaandlavetKeramikRoute: typeof PagesHaandlavetKeramikRoute
  PagesHvilkenKnivholderSkalJegVaelgeRoute: typeof PagesHvilkenKnivholderSkalJegVaelgeRoute
  PagesKnivholderITraeRoute: typeof PagesKnivholderITraeRoute
  PagesKnivholderTilKoekkenetRoute: typeof PagesKnivholderTilKoekkenetRoute
  PagesKoekkenetSomFristedRoute: typeof PagesKoekkenetSomFristedRoute
  PagesSaadanSliberDuDinKnivRoute: typeof PagesSaadanSliberDuDinKnivRoute
  PagesSadanHolderDuDinKnivSkarpRoute: typeof PagesSadanHolderDuDinKnivSkarpRoute
  PagesSlibestenGuideRoute: typeof PagesSlibestenGuideRoute
  PagesSommerbordMedKeramikRoute: typeof PagesSommerbordMedKeramikRoute
  ProductHandleRoute: typeof ProductHandleRoute
  RitualerHoldKnivenSkarpRoute: typeof RitualerHoldKnivenSkarpRoute
  RitualerRoligOpbevaringRoute: typeof RitualerRoligOpbevaringRoute
  UniversetSlugRoute: typeof UniversetSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  KeramikIndexRoute: typeof KeramikIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universet': {
      id: '/universet'
      path: '/universet'
      fullPath: '/universet'
      preLoaderRoute: typeof UniversetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returpolitik': {
      id: '/returpolitik'
      path: '/returpolitik'
      fullPath: '/returpolitik'
      preLoaderRoute: typeof ReturpolitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reklamation': {
      id: '/reklamation'
      path: '/reklamation'
      fullPath: '/reklamation'
      preLoaderRoute: typeof ReklamationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatlivspolitik': {
      id: '/privatlivspolitik'
      path: '/privatlivspolitik'
      fullPath: '/privatlivspolitik'
      preLoaderRoute: typeof PrivatlivspolitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handelsbetingelser': {
      id: '/handelsbetingelser'
      path: '/handelsbetingelser'
      fullPath: '/handelsbetingelser'
      preLoaderRoute: typeof HandelsbetingelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragt': {
      id: '/fragt'
      path: '/fragt'
      fullPath: '/fragt'
      preLoaderRoute: typeof FragtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-dit-ritual': {
      id: '/find-dit-ritual'
      path: '/find-dit-ritual'
      fullPath: '/find-dit-ritual'
      preLoaderRoute: typeof FindDitRitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookiepolitik': {
      id: '/cookiepolitik'
      path: '/cookiepolitik'
      fullPath: '/cookiepolitik'
      preLoaderRoute: typeof CookiepolitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cirklen': {
      id: '/cirklen'
      path: '/cirklen'
      fullPath: '/cirklen'
      preLoaderRoute: typeof CirklenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keramik/': {
      id: '/keramik/'
      path: '/keramik'
      fullPath: '/keramik/'
      preLoaderRoute: typeof KeramikIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universet_/$slug': {
      id: '/universet_/$slug'
      path: '/universet/$slug'
      fullPath: '/universet/$slug'
      preLoaderRoute: typeof UniversetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritualer/rolig-opbevaring': {
      id: '/ritualer/rolig-opbevaring'
      path: '/ritualer/rolig-opbevaring'
      fullPath: '/ritualer/rolig-opbevaring'
      preLoaderRoute: typeof RitualerRoligOpbevaringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritualer/hold-kniven-skarp': {
      id: '/ritualer/hold-kniven-skarp'
      path: '/ritualer/hold-kniven-skarp'
      fullPath: '/ritualer/hold-kniven-skarp'
      preLoaderRoute: typeof RitualerHoldKnivenSkarpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/sommerbord-med-keramik': {
      id: '/pages/sommerbord-med-keramik'
      path: '/pages/sommerbord-med-keramik'
      fullPath: '/pages/sommerbord-med-keramik'
      preLoaderRoute: typeof PagesSommerbordMedKeramikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/slibesten-guide': {
      id: '/pages/slibesten-guide'
      path: '/pages/slibesten-guide'
      fullPath: '/pages/slibesten-guide'
      preLoaderRoute: typeof PagesSlibestenGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/sadan-holder-du-din-kniv-skarp': {
      id: '/pages/sadan-holder-du-din-kniv-skarp'
      path: '/pages/sadan-holder-du-din-kniv-skarp'
      fullPath: '/pages/sadan-holder-du-din-kniv-skarp'
      preLoaderRoute: typeof PagesSadanHolderDuDinKnivSkarpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/saadan-sliber-du-din-kniv': {
      id: '/pages/saadan-sliber-du-din-kniv'
      path: '/pages/saadan-sliber-du-din-kniv'
      fullPath: '/pages/saadan-sliber-du-din-kniv'
      preLoaderRoute: typeof PagesSaadanSliberDuDinKnivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/koekkenet-som-fristed': {
      id: '/pages/koekkenet-som-fristed'
      path: '/pages/koekkenet-som-fristed'
      fullPath: '/pages/koekkenet-som-fristed'
      preLoaderRoute: typeof PagesKoekkenetSomFristedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/knivholder-til-koekkenet': {
      id: '/pages/knivholder-til-koekkenet'
      path: '/pages/knivholder-til-koekkenet'
      fullPath: '/pages/knivholder-til-koekkenet'
      preLoaderRoute: typeof PagesKnivholderTilKoekkenetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/knivholder-i-trae': {
      id: '/pages/knivholder-i-trae'
      path: '/pages/knivholder-i-trae'
      fullPath: '/pages/knivholder-i-trae'
      preLoaderRoute: typeof PagesKnivholderITraeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/hvilken-knivholder-skal-jeg-vaelge': {
      id: '/pages/hvilken-knivholder-skal-jeg-vaelge'
      path: '/pages/hvilken-knivholder-skal-jeg-vaelge'
      fullPath: '/pages/hvilken-knivholder-skal-jeg-vaelge'
      preLoaderRoute: typeof PagesHvilkenKnivholderSkalJegVaelgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/haandlavet-keramik': {
      id: '/pages/haandlavet-keramik'
      path: '/pages/haandlavet-keramik'
      fullPath: '/pages/haandlavet-keramik'
      preLoaderRoute: typeof PagesHaandlavetKeramikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/gaver-med-ro': {
      id: '/pages/gaver-med-ro'
      path: '/pages/gaver-med-ro'
      fullPath: '/pages/gaver-med-ro'
      preLoaderRoute: typeof PagesGaverMedRoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/gave-til-madelskeren': {
      id: '/pages/gave-til-madelskeren'
      path: '/pages/gave-til-madelskeren'
      fullPath: '/pages/gave-til-madelskeren'
      preLoaderRoute: typeof PagesGaveTilMadelskerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/den-forste-rigtige-kokkekniv': {
      id: '/pages/den-forste-rigtige-kokkekniv'
      path: '/pages/den-forste-rigtige-kokkekniv'
      fullPath: '/pages/den-forste-rigtige-kokkekniv'
      preLoaderRoute: typeof PagesDenForsteRigtigeKokkeknivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/damaskus-kniv': {
      id: '/pages/damaskus-kniv'
      path: '/pages/damaskus-kniv'
      fullPath: '/pages/damaskus-kniv'
      preLoaderRoute: typeof PagesDamaskusKnivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keramik/susan-riel': {
      id: '/keramik/susan-riel'
      path: '/susan-riel'
      fullPath: '/keramik/susan-riel'
      preLoaderRoute: typeof KeramikSusanRielRouteImport
      parentRoute: typeof KeramikRoute
    }
    '/keramik/$slug': {
      id: '/keramik/$slug'
      path: '/$slug'
      fullPath: '/keramik/$slug'
      preLoaderRoute: typeof KeramikSlugRouteImport
      parentRoute: typeof KeramikRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaver/fars-dag': {
      id: '/gaver/fars-dag'
      path: '/gaver/fars-dag'
      fullPath: '/gaver/fars-dag'
      preLoaderRoute: typeof GaverFarsDagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/handlavet-keramik': {
      id: '/collections/handlavet-keramik'
      path: '/collections/handlavet-keramik'
      fullPath: '/collections/handlavet-keramik'
      preLoaderRoute: typeof CollectionsHandlavetKeramikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CirklenRoute: CirklenRoute,
  CookiepolitikRoute: CookiepolitikRoute,
  FindDitRitualRoute: FindDitRitualRoute,
  FragtRoute: FragtRoute,
  HandelsbetingelserRoute: HandelsbetingelserRoute,
  KontaktRoute: KontaktRoute,
  OmRoute: OmRoute,
  PrivatlivspolitikRoute: PrivatlivspolitikRoute,
  ReklamationRoute: ReklamationRoute,
  ReturpolitikRoute: ReturpolitikRoute,
  ShopRoute: ShopRoute,
  UniversetRoute: UniversetRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  CollectionsHandlavetKeramikRoute: CollectionsHandlavetKeramikRoute,
  GaverFarsDagRoute: GaverFarsDagRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PagesDamaskusKnivRoute: PagesDamaskusKnivRoute,
  PagesDenForsteRigtigeKokkeknivRoute: PagesDenForsteRigtigeKokkeknivRoute,
  PagesGaveTilMadelskerenRoute: PagesGaveTilMadelskerenRoute,
  PagesGaverMedRoRoute: PagesGaverMedRoRoute,
  PagesHaandlavetKeramikRoute: PagesHaandlavetKeramikRoute,
  PagesHvilkenKnivholderSkalJegVaelgeRoute:
    PagesHvilkenKnivholderSkalJegVaelgeRoute,
  PagesKnivholderITraeRoute: PagesKnivholderITraeRoute,
  PagesKnivholderTilKoekkenetRoute: PagesKnivholderTilKoekkenetRoute,
  PagesKoekkenetSomFristedRoute: PagesKoekkenetSomFristedRoute,
  PagesSaadanSliberDuDinKnivRoute: PagesSaadanSliberDuDinKnivRoute,
  PagesSadanHolderDuDinKnivSkarpRoute: PagesSadanHolderDuDinKnivSkarpRoute,
  PagesSlibestenGuideRoute: PagesSlibestenGuideRoute,
  PagesSommerbordMedKeramikRoute: PagesSommerbordMedKeramikRoute,
  ProductHandleRoute: ProductHandleRoute,
  RitualerHoldKnivenSkarpRoute: RitualerHoldKnivenSkarpRoute,
  RitualerRoligOpbevaringRoute: RitualerRoligOpbevaringRoute,
  UniversetSlugRoute: UniversetSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  KeramikIndexRoute: KeramikIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
