/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OmRouteImport } from './routes/om'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as CirklenRouteImport } from './routes/cirklen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as PagesSadanHolderDuDinKnivSkarpRouteImport } from './routes/pages.sadan-holder-du-din-kniv-skarp'
import { Route as PagesGaveTilMadelskerenRouteImport } from './routes/pages.gave-til-madelskeren'
import { Route as PagesDenForsteRigtigeKokkeknivRouteImport } from './routes/pages.den-forste-rigtige-kokkekniv'
import { Route as PagesDamaskusKnivRouteImport } from './routes/pages.damaskus-kniv'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const CirklenRoute = CirklenRouteImport.update({
  id: '/cirklen',
  path: '/cirklen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSadanHolderDuDinKnivSkarpRoute =
  PagesSadanHolderDuDinKnivSkarpRouteImport.update({
    id: '/pages/sadan-holder-du-din-kniv-skarp',
    path: '/pages/sadan-holder-du-din-kniv-skarp',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesGaveTilMadelskerenRoute = PagesGaveTilMadelskerenRouteImport.update({
  id: '/pages/gave-til-madelskeren',
  path: '/pages/gave-til-madelskeren',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDenForsteRigtigeKokkeknivRoute =
  PagesDenForsteRigtigeKokkeknivRouteImport.update({
    id: '/pages/den-forste-rigtige-kokkekniv',
    path: '/pages/den-forste-rigtige-kokkekniv',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesDamaskusKnivRoute = PagesDamaskusKnivRouteImport.update({
  id: '/pages/damaskus-kniv',
  path: '/pages/damaskus-kniv',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cirklen': typeof CirklenRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/shop': typeof ShopRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/pages/damaskus-kniv': typeof PagesDamaskusKnivRoute
  '/pages/den-forste-rigtige-kokkekniv': typeof PagesDenForsteRigtigeKokkeknivRoute
  '/pages/gave-til-madelskeren': typeof PagesGaveTilMadelskerenRoute
  '/pages/sadan-holder-du-din-kniv-skarp': typeof PagesSadanHolderDuDinKnivSkarpRoute
  '/product/$handle': typeof ProductHandleRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cirklen': typeof CirklenRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/shop': typeof ShopRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/pages/damaskus-kniv': typeof PagesDamaskusKnivRoute
  '/pages/den-forste-rigtige-kokkekniv': typeof PagesDenForsteRigtigeKokkeknivRoute
  '/pages/gave-til-madelskeren': typeof PagesGaveTilMadelskerenRoute
  '/pages/sadan-holder-du-din-kniv-skarp': typeof PagesSadanHolderDuDinKnivSkarpRoute
  '/product/$handle': typeof ProductHandleRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cirklen': typeof CirklenRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/shop': typeof ShopRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/pages/damaskus-kniv': typeof PagesDamaskusKnivRoute
  '/pages/den-forste-rigtige-kokkekniv': typeof PagesDenForsteRigtigeKokkeknivRoute
  '/pages/gave-til-madelskeren': typeof PagesGaveTilMadelskerenRoute
  '/pages/sadan-holder-du-din-kniv-skarp': typeof PagesSadanHolderDuDinKnivSkarpRoute
  '/product/$handle': typeof ProductHandleRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cirklen'
    | '/kontakt'
    | '/om'
    | '/shop'
    | '/collections/$handle'
    | '/guides/$slug'
    | '/pages/damaskus-kniv'
    | '/pages/den-forste-rigtige-kokkekniv'
    | '/pages/gave-til-madelskeren'
    | '/pages/sadan-holder-du-din-kniv-skarp'
    | '/product/$handle'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cirklen'
    | '/kontakt'
    | '/om'
    | '/shop'
    | '/collections/$handle'
    | '/guides/$slug'
    | '/pages/damaskus-kniv'
    | '/pages/den-forste-rigtige-kokkekniv'
    | '/pages/gave-til-madelskeren'
    | '/pages/sadan-holder-du-din-kniv-skarp'
    | '/product/$handle'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/cirklen'
    | '/kontakt'
    | '/om'
    | '/shop'
    | '/collections/$handle'
    | '/guides/$slug'
    | '/pages/damaskus-kniv'
    | '/pages/den-forste-rigtige-kokkekniv'
    | '/pages/gave-til-madelskeren'
    | '/pages/sadan-holder-du-din-kniv-skarp'
    | '/product/$handle'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CirklenRoute: typeof CirklenRoute
  KontaktRoute: typeof KontaktRoute
  OmRoute: typeof OmRoute
  ShopRoute: typeof ShopRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PagesDamaskusKnivRoute: typeof PagesDamaskusKnivRoute
  PagesDenForsteRigtigeKokkeknivRoute: typeof PagesDenForsteRigtigeKokkeknivRoute
  PagesGaveTilMadelskerenRoute: typeof PagesGaveTilMadelskerenRoute
  PagesSadanHolderDuDinKnivSkarpRoute: typeof PagesSadanHolderDuDinKnivSkarpRoute
  ProductHandleRoute: typeof ProductHandleRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cirklen': {
      id: '/cirklen'
      path: '/cirklen'
      fullPath: '/cirklen'
      preLoaderRoute: typeof CirklenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/sadan-holder-du-din-kniv-skarp': {
      id: '/pages/sadan-holder-du-din-kniv-skarp'
      path: '/pages/sadan-holder-du-din-kniv-skarp'
      fullPath: '/pages/sadan-holder-du-din-kniv-skarp'
      preLoaderRoute: typeof PagesSadanHolderDuDinKnivSkarpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/gave-til-madelskeren': {
      id: '/pages/gave-til-madelskeren'
      path: '/pages/gave-til-madelskeren'
      fullPath: '/pages/gave-til-madelskeren'
      preLoaderRoute: typeof PagesGaveTilMadelskerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/den-forste-rigtige-kokkekniv': {
      id: '/pages/den-forste-rigtige-kokkekniv'
      path: '/pages/den-forste-rigtige-kokkekniv'
      fullPath: '/pages/den-forste-rigtige-kokkekniv'
      preLoaderRoute: typeof PagesDenForsteRigtigeKokkeknivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/damaskus-kniv': {
      id: '/pages/damaskus-kniv'
      path: '/pages/damaskus-kniv'
      fullPath: '/pages/damaskus-kniv'
      preLoaderRoute: typeof PagesDamaskusKnivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CirklenRoute: CirklenRoute,
  KontaktRoute: KontaktRoute,
  OmRoute: OmRoute,
  ShopRoute: ShopRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PagesDamaskusKnivRoute: PagesDamaskusKnivRoute,
  PagesDenForsteRigtigeKokkeknivRoute: PagesDenForsteRigtigeKokkeknivRoute,
  PagesGaveTilMadelskerenRoute: PagesGaveTilMadelskerenRoute,
  PagesSadanHolderDuDinKnivSkarpRoute: PagesSadanHolderDuDinKnivSkarpRoute,
  ProductHandleRoute: ProductHandleRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
